version: "3.9"

services:

  postgres:
    container_name: notification_db
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notification_db
#    volumes:
#      - postgres:/data/postgres
    ports:
      - "5434:5432"

##  networks and volumes
#  networks:
#    postgres:
#      driver: bridge

#  volumes:
#    postgres:
#    pgadmin: